# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time

name: Java CI with Maven

on:
  push:
    branches: [ "main", "vti-study" ]
  pull_request:
    branches: [ "main", "vti-study" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: cd i4driving-ots && mvn -B package --file pom.xml
    - run: cd i4driving-ots && mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v4
      with:
        name: 'OTS-i4driving'
        path: i4driving-ots/staging
